"""Celery worker that maps PSO particles to Phase 4 hydraulic simulations."""

from __future__ import annotations

import copy
import socket
from collections import defaultdict
from datetime import UTC, datetime
from math import inf
from typing import Any

from sqlalchemy import delete, select

from app.database.session import SessionLocal
from app.gis.models import (
    OptimizationCandidate,
    OptimizationResult,
    OptimizationTask,
    SimulationResult,
    SimulationTask,
    StructureResult,
)
from app.model_engine.provenance import ENGINE_VERSION
from app.worker.celery_app import celery_app
from app.worker.tasks import run_hydraulic_task
from model.metrics import evaluate_metrics
from model.provenance import snapshot_hash
from optimization.algorithms import ParticleSwarmOptimizer
from optimization.constraints import validate_candidate
from optimization.objectives import evaluate_objectives
from optimization.pareto import non_dominated_sort
from optimization.scheduler import build_dispatch_space
from model.solver.registry import MODEL_INPUT_V2, task_solver_provenance


def _dispatch_space(snapshot: dict[str, Any]) -> tuple[list[tuple[float, float]], list[dict[str, Any]]]:
    """Build particle bounds and a stable descriptor for every control gene."""

    bounds: list[tuple[float, float]] = []
    descriptors: list[dict[str, Any]] = []
    for gate in snapshot.get("gates", []):
        if gate.get("river_segment_id") is None:
            continue
        for slot in (0.0, 0.5):
            bounds.append((0.0, 1.0))
            descriptors.append({"structure_type": "gate", "asset": gate, "slot": slot})
    for pump in snapshot.get("pumps", []):
        maximum_units = int(pump.get("maximum_running_units") or pump.get("unit_count") or 1)
        for slot in (0.0, 0.5):
            bounds.append((0.0, float(max(maximum_units, 1))))
            descriptors.append({"structure_type": "pump", "asset": pump, "slot": slot})
    if not bounds:
        bounds.append((0.0, 1.0))
        descriptors.append({"structure_type": "noop", "asset": {}, "slot": 0.0})
    return bounds, descriptors


def _decode_plan(
    vector: tuple[float, ...],
    descriptors: list[dict[str, Any]],
    *,
    duration_seconds: float,
    objective_config: dict[str, Any],
) -> dict[str, Any]:
    """Decode one complete particle into a frozen Phase 4 dispatch plan."""

    actions: list[dict[str, Any]] = []
    previous_gate_ratio: dict[int, tuple[float, float]] = {}
    previous_pump_units: dict[int, tuple[float, float]] = {}
    for gene_index, (value, descriptor) in enumerate(zip(vector, descriptors, strict=True), 1):
        asset_type = descriptor["structure_type"]
        if asset_type == "noop":
            continue
        asset = descriptor["asset"]
        action_time = float(descriptor["slot"]) * duration_seconds
        target_value = float(value) if asset_type == "gate" else float(round(value))
        if asset_type == "gate":
            asset_id = int(asset["id"])
            previous = previous_gate_ratio.get(asset_id)
            if previous is not None:
                previous_time, previous_value = previous
                maximum_opening = float(asset.get("maximum_opening") or asset.get("height") or 1)
                rate_limit = float(asset.get("opening_rate_limit") or 1.0e9)
                maximum_ratio_change = rate_limit * (action_time - previous_time) / max(maximum_opening, 1e-9)
                target_value = min(previous_value + maximum_ratio_change, max(previous_value - maximum_ratio_change, target_value))
            previous_gate_ratio[asset_id] = (action_time, target_value)
        elif asset_type == "pump":
            asset_id = int(asset["id"])
            previous = previous_pump_units.get(asset_id)
            if previous is not None:
                previous_time, previous_value = previous
                if previous_value > 0 and target_value <= 0 and action_time - previous_time < float(asset.get("minimum_run_seconds") or 0):
                    target_value = previous_value
            previous_pump_units[asset_id] = (action_time, target_value)
        action = {
            "id": -gene_index,
            "sequence": gene_index,
            "time_seconds": action_time,
            "structure_type": asset_type,
            "gate_id": int(asset["id"]) if asset_type == "gate" else None,
            "pump_id": int(asset["id"]) if asset_type == "pump" else None,
            "command_type": "gate_opening_ratio" if asset_type == "gate" else "pump_unit_count",
            "target_value": target_value,
            "interpolation": "linear" if asset_type == "gate" else "step",
            "priority": 0,
            "note": "generated by dayu-pso-1.0.0",
        }
        actions.append(action)
    return {
        "schema_version": "dayu.dispatch-plan.v1",
        "plan": {
            "duration_seconds": duration_seconds,
            "evaluation_config": {
                "warning_level": objective_config.get("warning_level"),
                "guarantee_level": objective_config.get("guarantee_level"),
            },
            "storage_level": "full",
            "source": "optimization_candidate",
        },
        "actions": actions,
        "rules": [],
        "safety_notice": "simulation only; no command is sent to real equipment",
    }


def _build_candidate_simulation_task(
    optimization_task: OptimizationTask,
    candidate_snapshot: dict[str, Any],
    *,
    duration: float,
    algorithm: dict[str, Any],
) -> SimulationTask:
    """Build one v2 candidate task with Registry-owned route provenance."""

    return SimulationTask(
        case_id=optimization_task.simulation_case_id,
        dataset_version_id=optimization_task.dataset_version_id,
        status="queued",
        progress=0,
        config={
            "duration_seconds": duration,
            "time_step_seconds": algorithm["time_step_seconds"],
            "output_interval_seconds": algorithm["output_interval_seconds"],
            "storage_level": "full",
            "section_geometry": "rectangular",
            "allow_fallback_boundary": False,
        },
        input_schema_version=MODEL_INPUT_V2,
        input_snapshot=candidate_snapshot,
        input_snapshot_hash=snapshot_hash(candidate_snapshot),
        engine_version=ENGINE_VERSION,
        engine_commit=(candidate_snapshot.get("provenance") or {}).get(
            "engine_commit", "uncommitted"
        ),
        queued_time=datetime.now(UTC),
        **task_solver_provenance(MODEL_INPUT_V2),
    )


def _candidate_metrics(task_id: int) -> dict[str, Any]:
    """Aggregate all persisted Phase 4 section and structure evidence."""

    with SessionLocal() as session:
        task = session.get(SimulationTask, task_id)
        rows = session.scalars(
            select(SimulationResult)
            .where(SimulationResult.task_id == task_id)
            .order_by(SimulationResult.section_code, SimulationResult.time_seconds)
        ).all()
        grouped: dict[str, list[SimulationResult]] = defaultdict(list)
        for row in rows:
            grouped[row.section_code].append(row)
        section_series = [
            {
                "section_code": code,
                "time": [row.time_seconds for row in items],
                "water_level": [row.water_level for row in items],
            }
            for code, items in grouped.items()
        ]
        structures = [
            {
                "structure_type": row.structure_type,
                "structure_id": row.structure_id,
                "time_seconds": row.time_seconds,
                "actual_value": row.actual_value,
                "flow": row.flow,
                "power_kw": row.power_kw,
                "energy_kwh": row.energy_kwh,
                "constraint_flags": row.constraint_flags,
            }
            for row in session.scalars(
                select(StructureResult)
                .where(StructureResult.task_id == task_id)
                .order_by(StructureResult.time_seconds)
            ).all()
        ]
        objective_config = ((task.input_snapshot or {}).get("dispatch_plan") or {}).get("plan", {}).get("evaluation_config", {}) if task else {}
        metrics = evaluate_metrics(
            section_series=section_series,
            structure_series=structures,
            diagnostics=task.diagnostics or {} if task else {},
            evaluation_config=objective_config,
        )
        metrics["network_maximum_flow"] = max((abs(row.flow) for row in rows), default=0.0)
        representative_code = sorted(grouped)[0] if grouped else None
        representative_rows = grouped.get(representative_code or "", [])
        metrics["comparison_series"] = {
            "section_code": representative_code,
            "time": [row.time_seconds for row in representative_rows],
            "water_level": [row.water_level for row in representative_rows],
            "flow": [row.flow for row in representative_rows],
            "gates": [item for item in structures if item["structure_type"] == "gate"],
            "pumps": [item for item in structures if item["structure_type"] == "pump"],
        }
        return metrics


def _finalize_pareto(session: Any, task: OptimizationTask) -> None:
    """Assign levels/ranks and select the weighted best first-front candidate."""

    session.execute(delete(OptimizationResult).where(OptimizationResult.task_id == task.id))
    candidates = list(
        session.scalars(
            select(OptimizationCandidate)
            .where(OptimizationCandidate.task_id == task.id)
            .order_by(OptimizationCandidate.id)
        ).all()
    )
    valid = [item for item in candidates if item.valid and item.objective_values]
    vectors = [
        [
            float(item.objective_values["values"]["flood_risk"]),
            float(item.objective_values["values"]["energy_cost"]),
            float(item.objective_values["values"]["operation_cost"]),
        ]
        for item in valid
    ]
    valid_levels = non_dominated_sort(vectors) if vectors else []
    levels = {item.id: valid_levels[index] for index, item in enumerate(valid)}
    rejected_level = max(valid_levels, default=0) + 1
    recommended = min(
        (item for item in valid if levels[item.id] == 1),
        key=lambda item: (float(item.score or inf), item.id),
        default=None,
    )
    rank_by_level: dict[int, int] = defaultdict(int)
    for candidate in sorted(
        candidates,
        key=lambda item: (levels.get(item.id, rejected_level), float(item.score or inf), item.id),
    ):
        level = levels.get(candidate.id, rejected_level)
        rank_by_level[level] += 1
        status = (
            "rejected"
            if not candidate.valid
            else "recommended"
            if recommended is not None and candidate.id == recommended.id
            else "pareto"
            if level == 1
            else "alternative"
        )
        session.add(
            OptimizationResult(
                candidate_id=candidate.id,
                task_id=task.id,
                pareto_level=level,
                rank=rank_by_level[level],
                recommendation_status=status,
                explanation={
                    "type": "deterministic_template",
                    "reason": "lowest_weighted_score_on_first_pareto_front" if status == "recommended" else status,
                    "human_review_required": True,
                },
            )
        )


@celery_app.task(bind=True, name="dayu.run_optimization_task")
def run_optimization_task(self: Any, task_id: int) -> dict[str, str | int]:
    """Run seeded PSO while delegating every valid candidate to the Phase 4 worker."""

    with SessionLocal() as session:
        task = session.get(OptimizationTask, task_id)
        if task is None or task.status != "running":
            return {"task_id": task_id, "status": "ignored"}
        task.worker_id = f"{socket.gethostname()}:{self.request.id or 'eager'}"
        session.commit()
        try:
            optimization_snapshot = task.input_snapshot
            hydraulic_snapshot = optimization_snapshot["hydraulic_input"]
            algorithm = task.algorithm_config
            objective_config = task.objective_config
            constraints = algorithm["constraints"]
            duration = float(algorithm["duration_seconds"])
            bounds, descriptors = build_dispatch_space(hydraulic_snapshot)
            gates = list(hydraulic_snapshot.get("gates", []))
            pumps = list(hydraulic_snapshot.get("pumps", []))

            def cancelled() -> bool:
                """Refresh cooperative cancellation state between candidates."""

                session.expire(task)
                return bool(task.cancel_requested)

            def evaluate(vector: tuple[float, ...], generation: int, index: int) -> float:
                """Persist a candidate, run Phase 4 and return its penalized score."""

                plan = _decode_plan(
                    vector,
                    descriptors,
                    duration_seconds=duration,
                    objective_config=objective_config,
                )
                precheck = validate_candidate(
                    plan, gates=gates, pumps=pumps, config=constraints
                )
                candidate = OptimizationCandidate(
                    task_id=task.id,
                    generation=generation,
                    candidate_index=index,
                    dispatch_plan=plan,
                    valid=precheck.valid,
                    constraint_reasons=list(precheck.reasons),
                )
                session.add(candidate)
                session.commit()
                session.refresh(candidate)
                metrics: dict[str, Any] = {}
                reasons = list(precheck.reasons)
                if precheck.valid:
                    candidate_snapshot = copy.deepcopy(hydraulic_snapshot)
                    candidate_snapshot["dispatch_plan"] = plan
                    candidate_snapshot.setdefault("provenance", {})["optimization_candidate_id"] = candidate.id
                    simulation = _build_candidate_simulation_task(
                        task,
                        candidate_snapshot,
                        duration=duration,
                        algorithm=algorithm,
                    )
                    session.add(simulation)
                    session.commit()
                    candidate.simulation_task_id = simulation.id
                    session.commit()
                    worker_result = run_hydraulic_task.run(simulation.id)
                    if worker_result.get("status") == "success":
                        metrics = _candidate_metrics(simulation.id)
                        postcheck = validate_candidate(
                            plan,
                            gates=gates,
                            pumps=pumps,
                            config=constraints,
                            metrics=metrics,
                        )
                        reasons.extend(postcheck.reasons)
                    else:
                        reasons.append(f"simulation:{worker_result.get('status', 'failed')}")
                objectives = evaluate_objectives(metrics, objective_config)
                valid = not reasons
                score = float(objectives["score"])
                if not valid:
                    score += float(constraints["invalid_penalty"]) * max(len(set(reasons)), 1)
                candidate.metrics = metrics
                candidate.objective_values = objectives
                candidate.valid = valid
                candidate.constraint_reasons = list(dict.fromkeys(reasons))
                candidate.score = score
                session.commit()
                return score

            def report(generation: int, best_score: float) -> None:
                """Persist convergence history after each full generation."""

                task.current_generation = generation
                task.best_score = best_score
                task.progress = min(99, int(100 * generation / int(algorithm["max_iterations"])))
                session.commit()

            optimizer = ParticleSwarmOptimizer(
                bounds,
                particle_count=int(algorithm["particle_count"]),
                max_iterations=int(algorithm["max_iterations"]),
                inertia=float(algorithm["inertia"]),
                cognitive=float(algorithm["cognitive"]),
                social=float(algorithm["social"]),
                tolerance=float(algorithm["tolerance"]),
                patience=int(algorithm["patience"]),
                seed=int(algorithm["seed"]),
            )
            optimizer.optimize(evaluate, should_cancel=cancelled, on_generation=report)
            session.expire(task)
            if task.cancel_requested:
                task.status = "cancelled"
            else:
                _finalize_pareto(session, task)
                task.status = "success"
                task.converged = optimizer.converged
            task.progress = 100
            task.end_time = datetime.now(UTC)
            session.commit()
            return {"task_id": task_id, "status": task.status}
        except Exception as exc:
            session.rollback()
            task = session.get(OptimizationTask, task_id)
            if task is not None:
                task.status = "failed"
                task.progress = 100
                task.error_message = str(exc)[:4000]
                task.end_time = datetime.now(UTC)
                session.commit()
            return {"task_id": task_id, "status": "failed"}
